### ISSUE TITLE
decentralize freenet even more using a consensus?

### ISSUE THREAD

**Issue by gogo2464** [freenet/freenet-core#1024]
Hello.

I would like to create an out proxy. it is particulary necessary because I would like to communicate to my freenet contract using command line.

Sadly I fear I could be going to kill freenet because an internet to freenet proxy will centralize freenet.

I suggest to add a consensus.

The consensus SHALL be punitive and SHALL NO provide reward to the user. The goal is to block website from having too much connection to freenet for each user.

I do not want to remunerate peer because people go crazy with money. Instead I would like to simply block the access of people not providing enough ressources such as data storage.

I am not a cryptographer. I may say stupid stuff.

Best regards.

**Comment by sanity** [comment]
This is too vague, we can discuss on Matrix.
