### ISSUE TITLE
improove freenet-core modularity even more

### ISSUE THREAD

**Issue by gogo2464** [freenet/freenet-core#1194]
Hello,

I realized there have been great progress in freenet modularity by splitting:
- web hosting
- privacy protection

I suggest to improove modularity even more by splitting:

- web hosting
- DNS
- etc...

So that people could reuse DNS in their own project not related to freenet.

**Comment by sanity** [comment]
Too vague.

**Comment by gogo2464** [comment]
I would like to expose the freenet dns as a public crate.

And then I may write javascript bindings usable in nodejs.

**Comment by gogo2464** [comment]
The freenet code USED TO be confused. as it is not anymore,

I would like to have different crates for parts there:
https://github.com/freenet/freenet-core/tree/fe30af6b79e1bc391f7dea45efc57c3611fc3a02/crates/core/src/transport

I think is is already done.
