### ISSUE TITLE
Improved transactions data sent in network monitor

### ISSUE THREAD

**Issue by alexisbatyk** [freenet/freenet-core#1195]
Tasks included on this issue: 
- [x] Add contracts_data to ServerState in network_metrics_server.rs in fdev. 
- [x] Task included: Send all transaction history when the ws connection starts.
- [x] Task included: Store contract data on fn save_record when pushing a new event.

**Comment by alexisbatyk** [comment]
Task included: [Add contracts_data to ServerState in network_metrics_server.rs in fdev. ](https://github.com/orgs/freenet/projects/2?pane=issue&itemId=74531321)

**Comment by alexisbatyk** [comment]
Task included: Send all transaction history when the ws connection starts.

**Comment by alexisbatyk** [comment]
Task included: Store contract data on `fn save_record` when pushing a new event.

**Comment by iduartgomez** [comment]
@alexisbatyk can we close this issue?

**Comment by iduartgomez** [comment]
Done, re-opem if necessary @alexisbatyk
