### ISSUE TITLE
Switch to RocksDB store back end as default storage

### ISSUE THREAD

**Issue by iduartgomez** [freenet/freenet-core#17]
In the future build with both Sqlite and RocksDB as possible backends (via feature) in order to compare behavior and performance characteristics. Probably we will want to stick with one, eventually, but otherwise, RocksDB can be used as a building block  KV for more complex databases (is already used as such for distributed databases ala TiKV, for example), but it does not have SQL semantics on top of it, unlike Sqlite, which could prove useful.

In any case demonstrating we can quickly swap between store backends is benefitial so we are not stuck and coupled with one (and since right now we only need to maintain simple key-value semantics is rather easy to keep the backend implementation decoupled from the rest of the application, something we would like to continue in the future).

**Comment by kakoc** [comment]
I'll tackle on that
