### ISSUE TITLE
Document the app development process

### ISSUE THREAD

**Issue by sanity** [freenet/freenet-core#189]
We need to document the process of writing and compiling contracts, and writing web apps that communicate with the node via websocket.

We can keep this low-level and general so that others can use it to build convenience tools like an assemblyscript wrapper for contracts, or a friendly API for websocket communication.

**Comment by sanity** [comment]
Probably makes sense to document it on a [wiki](https://github.com/freenet/locutus/wiki) page 

cc: @iduartgomez

**Comment by iduartgomez** [comment]
@sanity I am thinking of using a "gitbook" (https://www.gitbook.com/ free for open source projects), some of the reasons of using it over a wiki are:
- you get access to version control and pin documentation to certain versions of the software
- documentation as code
- can build documentation on CI pipelines and deploy it

Also it has a nice feeling a defaults.

**Comment by sanity** [comment]
@iduartgomez Haven't used it but looks similar to https://readthedocs.org/ which I have used, sounds good.

**Comment by iduartgomez** [comment]
Duplicate of #265 (sorry forgot about this one @sanity)
