### ISSUE TITLE
Create a test contract for testing purposes

### ISSUE THREAD

**Issue by netsirius** [freenet/freenet-core#276]
The goal of this issue is to have a test contract that allows interaction on the state in the tests that require it. Changes required:

- Generate a simple compiled contract available for modules where interaction with the contract is required.

Currently these tests are ignored and marked with the comment:
`// FIXME: Generate required test contract`

**Comment by iduartgomez** [comment]
We will take care of this in #337 since was necessary to test out the changes in the API anyway.
