### ISSUE TITLE
Use Bech32 instead of Base58 for keys.

### ISSUE THREAD

**Issue by stevenj** [freenet/freenet-core#365]
Ref: https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki
The proposal is as stated, instead of using unadorned Base58, use Bech32 because it has a number of useful properties:
1. Well specified, and used by others in the space.
2. Allows a human readable prefix, so we can differentiate addresses between test networks and production networks, even if they refer the the same contracts and parameters, we could even use the human readable prefix to identify webapp contracts vs standard contracts, etc.
3. Contains a checksum, so Invalid keys can be detected without any network activity required to fail to find them.
4. There are Rust libraries that already handle Bech32.

It is acknowledged that #3 does not protect from a validly formed Key that has been randomly created (maliciously?).

**Comment by stevenj** [comment]
FYI,  I am happy to make the necessary PR if this is accepted.

**Comment by iduartgomez** [comment]
Initially I thought of using base64 but went with base58 cause is more human readable (no weird padding characters) and has nice alphabet.

The points stated in the referenced issue all seem quite rational to me so I am not against this, but why shouldn't we just change to base64 if we are going to make a change?

EDIT: take in mind keys are used for creating paths in the filesystem in case of resulting strange characters

**Comment by stevenj** [comment]
The original source has a lot of great points why it was selected,  base58 was designed to avoid miskeying for similar looking characters.  Bech32 goes further, so that you can read out a particular key to someone and there is no upper/lower case ambiguity.

Base64 would not have the "human readable part" which can be used to discriminate the types of keys or the network they are for, and does not have the check digits to check for user error if they keyed it in.  This last one is really important if there will ever be a scenario where a user will key in a contract address,  the UI they are given can refuse to proceed until the address is valid, so edit mistakes are caught early and interactively.  It also helps the user know the difference between a contract key that can not be found, and one thats actually just bogus.

**Comment by iduartgomez** [comment]
@sanity sounds reasonable to me, should we go ahead with this?

**Comment by sanity** [comment]
I agree that a check digit is valuable. I'm less sure about the necessity of it being human-readable as there are [much better](https://gist.github.com/fogleman/c4a1f69f34c7e8a00da8) solutions for that, but a slightly longer key seems like a small price to pay for reducing the chance of mistakes.

**Comment by iduartgomez** [comment]
Ok perfect

**Comment by stevenj** [comment]
I will work up a PR and you can review if you like.

**Comment by iduartgomez** [comment]
Decided against doing this finally, as contract identitfiers will rarely be used directly by end users and is not worth the trouble at the cost of a slight loss in efficiency.
