### ISSUE TITLE
RFC: Hash the Key like a merkel tree, rather than a hash of the whole contract + parameters.

### ISSUE THREAD

**Issue by stevenj** [freenet/freenet-core#366]
Currently the key is hashed based on the concatenation of the Contract Data and the Parameters.
The proposal here is, treat the hashing like a merke tree with a fixed number of leaves.  
```mermaid
classDiagram
    ContractKey <|-- ContractHash
    ContractKey <|-- ParameterHash

    ContractHash <|-- Contract
    ParameterHash <|-- Parameters

    class ContractKey{
        contract_key: bytes
        hash(concat(contract_hash, parameter_hash))
    }

    class ContractHash{
        contract_hash : bytes
        hash(Contract.as_bytes())
    }

    class ParameterHash{
        parameter_hash
        hash(Paramters.as_bytes())
    }

    class Contract{
        Compiled Wasm
        as_bytes()
    }

    class Parameters{
        Structured Parameter Data
        as_bytes()
    }    
```
The rationale is,  a Given Web App, or another Contract, can synthesize the address of any other related contract, and all it would need is the Hash of the Contract Wasm code.  It can generate the Parameters its looking for, hash those, and then get the Key for that contract.

Without this, we need the entire contract to do the same operation.

Practical Example.  A permission-less private email system.  If I know that Dave has a public key (12345678),  I can look for a contract key that is the `hash( hash(email contract) + hash(daves public key))`.  If that contract exists, I can encrypt my message with daves public key, and add it to the contracts state.  Dave then is the only one who can read/decrypt the message, and all he needs to do is enter his private key into the email webapp to both retrieve the contract from the network, and decrypt his email.  Further, Dave could be the only one who could actually make the contract for his email, because the initial state could be a proof that dave actually does have the public key that is the contract parameter, and the contract validation can require this proof.

**Comment by stevenj** [comment]
FYI,  I am happy to make the necessary PR if this is accepted.

**Comment by sanity** [comment]
It's not quite the same as you're proposing, but we have considered that issue with our current approach, which is:

`contract_instance_id = hash(hash(web_assembly), parameters)`

This avoids storing duplicate contract `web_assembly` and also allows the construction of keys without needing the full `web_assembly,` just it's hash.

Seems like you're suggesting `hash(hash(web_assembly), hash(parameters))`, does that have advantages over just using the parameters directly?

**Comment by stevenj** [comment]
No, either works fine,  because you need the parameters regardless.
