### ISSUE TITLE
Network simulation and automated performance testing

### ISSUE THREAD

**Issue by sanity** [freenet/freenet-core#377]
Debugging sophisticated P2P networks when actually deployed is extremely difficult, and they almost always require a considerable amount of debugging. 

The solution is to simulate actual node behavior under realistic and worst-case network conditions before the network goes live.

I propose to make it possible to run a large number (more is better) of Locutus peers on a single machine using a local network layer, that can simulate realistic latency and packet loss between them (perhaps using a tool like [traffic control](https://man7.org/linux/man-pages/man8/tc.8.html).

While not all part of the MVP, this could then be used to simulate:

* Building the network and maintaining a small-world topology
* Ability to handle peer failure
* Reduced network speed and reliability
* Contract state retrieval, subscription, and update propagation
* Malicious peers

Smaller simulations could run as part of our CI process to detect any obvious performance regressions, larger simulations could run as-needed on large cloud instances.

Example metrics to track under a variety of scenarios:

* Contract time for initial retrieval after insert
* Contract update propagation latency, average + worse case

Questions:

- [ ] Is it more efficient for all peers to run in the same process, or a separate process for each?

**Comment by sanity** [comment]
May be useful: http://imunes.net/

**Comment by iduartgomez** [comment]
Trackign this as an epic in PT
