### ISSUE TITLE
State[Store|Storage]: make it possible to remove

### ISSUE THREAD

**Issue by kakoc** [freenet/freenet-core#462]
Currently we are able to store/get contracts + params.  
Does it make sense to be able to remove them?

**Comment by iduartgomez** [comment]
The node will remove any malicious contracts in the future when we have the proper detection mechanisms in place (is planned) automatically, but in case a user or application wanted to remove certain contracts it makes sense the to add the option to the command API and should be relatively straightforward.

We haven't added it yet cause it was not a priority probably since the API is much in flux.

@sanity you see any problem with supporting this?

**Comment by sanity** [comment]
Hmm, what is the use case? Just local testing of contracts?

As you said, the node will do automatic housekeeping in the future, but if there is a strong use case for a temporary solution then I don't have a problem with it.

**Comment by kakoc** [comment]
I thought about cases when I accidentally deployed a contract with the wrong internal logic. So that I'd like to remove it for example. Or what if I'd like to have a contract with some expiry date(btw probably it can be implemented as an option from the locutus side? anyway what if a user forget about that functionality) so that I want to remove it after certain point of time?

**Comment by iduartgomez** [comment]
You mean removing it locally? Once the contract is out in the network it may be impossible to completely remove it. Having an expiry option may be t he only way of removing it and I actually don't dislike that option, may be useful for certain ephimeral contracts.

The suggested good practice will have to have a front bridge contract that will handle versioning automatically so applications can migrate versions easily.

The use case I was thinking for was for example in applications where the app wouldn't care about a particular contract instance anymore. Example: a messaging application which keeps track of the different DMs through different instances and you want to block or remove a particular conversation, then the app could clean up a useless contract instance.

**Comment by kakoc** [comment]
> Once the contract is out in the network it may be impossible to completely remove it.   

Yeah, I meant that problem.

> Example: a messaging application which keeps track of the different DMs through different instances and you want to block or remove a particular conversation, then the app could clean up a useless contract instance.  

Yeah, I think that we should have a mechanics which allow us resolve such problems. Not only following best practices

**Comment by iduartgomez** [comment]
Well, is physically impossible to guarantee that a contract is completely removed from the network, just like is impossible to remove bad versions of any released software of all existing machines, you just patch them up and release a new one, and the nodes should pick that up if you do it through a frontend application/contract. But we could do it in a best effort basis.

There are practical problems with supporting delete commands over the network, for instance, for how long such command should be propagated? Must think a bit more about this. Locally removing a contract I don't see a problem with.

**Comment by sanity** [comment]
> @kakoc I thought about cases when I accidentally deployed a contract with the wrong internal logic. So that I'd like to remove it for example.

The contract's key is derived from its WebAssembly code plus any parameters, so if the logic changes, or the parameters change, then the key changes. I don't see an advantage to being able to remove it - nobody will find it unless they have the key.

If the contract's **state** needs to be updated then that's a different matter, the contract's design should allow the state to be updated - but this is up to the contract's author.

"State" refers to the "value" corresponding to the contract's key, and shouldn't be confused with the contract's webassembly code or its parameters.

**Comment by sanity** [comment]
Please reopen if still relevant.
