### ISSUE TITLE
Web and websocket interface

### ISSUE THREAD

**Issue by sanity** [freenet/freenet-core#79]
### Purpose

A web browser can be used as a general-purpose user interface for decentralized applications on Locutus. These applications can be distributed via Locutus and interface with Locutus through an efficient WebSocket connection to a user's Locutus node.

This is analogous to [FProxy](https://github-wiki-see.page/m/freenet/wiki/wiki/FProxy) in Fred, but much more powerful because it supports interactive web applications.

### HTTP gateway

* Listens for HTTP connections which include a contract hash, eg. `http://127.0.0.1:8608/3M3fbA7RDYdvYeaoR69cDCtVJqEodo9vth`
* Contract state consists of metadata and  a "payload" - each prefixed by a `u32` length. 
  * The payload a `tar.xz` file containing a website including `index.html`
  * The metadata may include things like a digital signature to be verified by the contract.
* All files in payload will be made available on the requested URL, eg. `http://127.0.0.1:8608/3M3fbA7RDYdvYeaoR69cDCtVJqEodo9vth/index.html`

**todo:** Also needs to support redirect mechanism, so instead of a payload the address of another contract is given - the gateway will transparently redirect to that. This redirect will be updatable which will allow contract versioning.

### WebSocket

A connection to the gateway may be [upgraded](https://developer.mozilla.org/en-US/docs/Web/HTTP/Protocol_upgrade_mechanism) to a websocket that can be used to get, put, and modify contract state

#### WebSocket commands

WebSocket messages are encoded in a binary serialization format such as MessagePack (TBD).

The following commands and responses are supported:

```rust
mod get {
    /// Client -> Node
    struct Request {
        key : Vec<u8>,
        request_contract : bool,
        subscribe : bool,
    }

    /// Node -> Client
    struct Response {
        contract : Option<Vec<u8>>,
        subscription_id : Option<u64>,
        state : Vec<u8>,
    }

    // Node -> Client
    struct Notify {
        subscription_id : u64,
        state : Vec<u8>,
    }
}

mod put {
    /// Client -> Node
    struct Request {
        contract : Vec<u8>,
        state : Vec<u8>,
    }

    /// Node -> Client
    struct Response {

    }
}

mod update {
    /// Client -> Node
    struct Request {
        contract : Vec<u8>,
        delta : Vec<u8>,
    }
    
    /// Node -> Client
    struct Response {

    }
}
```

### Proxy

This HTTP interface can also serve as a HTTP proxy, which will only permit connections through this interface. This can be used to prevent applications from connecting to non-Locutus websites.

**Comment by iduartgomez** [comment]
**TODO**: Also needs to support redirect mechanism, so instead of a payload the address of another contract is given - the gateway will transparently redirect to that. This redirect will be updatable which will allow contract versioning.

**Comment by iduartgomez** [comment]
We have a working implementation of the http gateway and websocket interface so can consider this completed for the first version.
