### ISSUE TITLE
Lots of "cannot find x in this scope" errors

### ISSUE THREAD

**Issue by krionical** [freenet/freenet-core#880]
When running through the example app [here](https://docs.freenet.org/tutorial.html?search=)  I issue fdev build in the web app directory  and get a lot of "cannot find macro 'concat' in this scope and so on.  See attachment for further details.

[gitissuesforfreenetsan.txt](https://github.com/freenet/freenet-core/files/13145670/gitissuesforfreenetsan.txt)

**Comment by iduartgomez** [comment]
What's you rust version? `rustc --version`
If is lower than 1.71 could you update it? (In case you installed using `rustup`, just run  `rustup update`).

This is not an issue directly related to `fdev` or  `freenet`.

**Comment by krionical** [comment]
Version was 1.72.1 and I updated it to 1.73.0. Fewer errors are now reported. 150. Still find out of scope and undeclared type. It sounds like if this issue is neither related to fdev or freenet then this isn't the place for it.

**Comment by iduartgomez** [comment]
Still can try helping out, or check that everything is correct... It could be a problem of building a dependency for a target without the proper featurs too.

If you describe the exact steps to reproduce the problem I can rey it out.

**Comment by krionical** [comment]
Probably faster would be if there is a known working repo with the demo app. If I run that and it runs right, then it is down to something weird happening in my personal build process and reading the docs.

**Comment by iduartgomez** [comment]
You can fin the app in this same repo under:
https://github.com/freenet/freenet-core/tree/main/apps/freenet-email-app

Follow the instructions in the readme, tried with the `main` branch, everything still works correctly.

**Comment by krionical** [comment]
All right. So I go to the folder identity-management and run make build and get this:

Makefile:9: *** CARGO_TARGET_DIR is not set.  Stop.

**Comment by iduartgomez** [comment]
Right, you need to set it manually when you run the command
`export CARGO_TARGET_DIR="/path/to/my/target/dir"`
that's usually in `./target` by default that's where cargo sets it up (if it sets it up) but it can wherever you want to dump your build artifacts.

**Comment by krionical** [comment]
All right. I thought it might be something like that, but didn't see it in the readme instructions, so I just followed what was written. Your above advice allows me to dig a deep
[giterrorsemailsan.txt](https://github.com/freenet/freenet-core/files/13179559/giterrorsemailsan.txt)
er hole. I'll attach the results.

**Comment by iduartgomez** [comment]
I see in the logs:
```
 the `wasm32-unknown-unknown` target may not be installed`
```

oh, this is also missing from instructions...

Need to do `cargo target add wasm32-unknown-unknown`.

**Comment by krionical** [comment]
In response to that command I get this:

error: no such command: `target`

	Did you mean `tree`?

**Comment by iduartgomez** [comment]
Sorry, not cargo, mixed up utils, "rustup add target"

**Comment by krionical** [comment]
that command gives me:
Modify a toolchain's supported targets

USAGE:
    rustup target <SUBCOMMAND>

OPTIONS:
    -h, --help    Print help information

SUBCOMMANDS:
    list      List installed and available targets
    add       Add a target to a Rust toolchain
    remove    Remove a target from a Rust toolchain
    help      Print this message or the help of the given subcommand(s)
    
    If I issue what I think is the form it is wanting I type this: 
    
    rustup target add ./target
    
    Since if I don't add the directory it complains about not having a target. If that's right, then I get this back:
    
    error: toolchain 'stable-x86_64-unknown-linux-gnu' does not contain component 'rust-std' for target './target'
note: not all platforms have the standard library pre-compiled: https://doc.rust-lang.org/nightly/rustc/platform-support.html

    
   Digging around on the internet I tried this: rustup default stable:
   
   and it chirps back: info: using existing install for 'stable-x86_64-unknown-linux-gnu'
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.73.0 (cc66ad468 2023-10-03)

All of which ends with the same errors I had when I began following the directions for the email client.  I'm starting to feel like the village idiot since I don't have a lot of experience with rust, but maybe that's useful since there could be others that are going to try to use freenet that won't have that experience?

**Comment by iduartgomez** [comment]
Yeah, need clear instructions on this, docs are missing somethings, we can improve that. Pretty sure then that what you want is:

`rustup target add wasm32-unknown-unknown`

This command adds that target for cross-compilation. wasm target is necessary cause that's what we want to compile the contract too.

Does not help I am saying all this from memory...

**Comment by krionical** [comment]
Great Success! That part built! Switching over to anti-flood however after make build:

 make build
cd /home/freenet/freenet-core/modules/antiflood-tokens/contracts/token-allocation-record
fdev build
Compiling contract with rust
    Updating crates.io index
error: failed to get `freenet-stdlib` as a dependency of package `freenet v0.0.6 (/home//freenet/freenet-core/crates/core)`
    ... which satisfies path dependency `freenet` of package `freenet-token-generator v0.1.0 (/home//freenet/freenet-core/modules/antiflood-tokens/delegates/token-generator)`

Caused by:
  failed to load source for dependency `freenet-stdlib`

Caused by:
  Unable to update /home/freenet/freenet-core/stdlib/rust

Caused by:
  failed to read `/home/freenet/freenet-core/stdlib/rust/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
Error: exit with status: exit status: 101
make: *** [Makefile:29: build-token-allocation-contract] Error 1


Maybe this will help others and can be added to the docs?

**Comment by iduartgomez** [comment]
This is more specific to this repo, the app will be moved to other repo sooner rather than later so that shouldn't happen. But yes this can be added to the readme.

Meanwhile you need to do "git submodule update".

Maybe you can continue with the guide now, maybe the errors you were getting are fixed now.

**Comment by krionical** [comment]
If I run that at the freenet-core level it doesn't report anything back. So, I tried it in the module directory as well, and it also didn't say anything back which I took to mean "everything is fine". However, make build still generates the above error in the directory for anti-flood. Also, git status shows everything being up to date.

**Comment by iduartgomez** [comment]
Well if the directory is there indeed and you only get the error in one directory that's just weird and sounds like a git issue?

One thing you can do then is point to the published one instead of using the path dependency (like `freenet-std = "0.0.8"`) , but you will need to change it in all dependencies (antiflood-token, identity-manager, etc.)

At this point I think we will be better of splitting that on it's own repo.

**Comment by krionical** [comment]
If I change that in the cargo.toml as indicated it throws this:

Compiling contract with rust
error: failed to parse manifest at `/home/freenet/freenet-core/modules/antiflood-tokens/contracts/token-allocation-record/Cargo.toml`

Caused by:
  error inheriting `freenet-stdlib` from workspace root manifest's `workspace.dependencies.freenet-stdlib`

Caused by:
  `dependency.freenet-stdlib` was not found in `workspace.dependencies`
Error: exit with status: exit status: 101
make: *** [Makefile:29: build-token-allocation-contract] Error 1

I think we are getting to a place where my lack of skill with rust is likely to hinder whatever is happening. I can see that in the other toml the dependency doesn't seem to be an issue, but for whatever reason it does in this one. I'm willing to simply state that something about my system/git is peculiar compared to the main systems that people may be using to build. I'm on opensuse, so that could be a variable.

**Comment by krionical** [comment]
Update: So I re-cloned this whole repo with the following after some internet digging: git clone --recurse-submodules https://github.com/freenet/freenet-core.git 

Which I found on this thread: https://www.reddit.com/r/rust/comments/f8cd61/cargo_build_giving_me_cargotoml_file_not_found/

So far, both identity and antiflood builds. I'm gonna take a break and update the thread later when I see if the interface also builds.

**Comment by krionical** [comment]
All right, everything seems to build except for the email web app. When I type in make run-web I get the following:

cd /home//freenet/freenet-core/apps/freenet-email-app/web
dx build --target index.html --platform web --features use-node
dx serve --features use-node --port 57616
/bin/sh: line 2: dx: command not found
/bin/sh: line 3: dx: command not found
make: *** [Makefile:50: run-web] Error 127

I gather this is dioxus for rust. 

If I run the cargo add dioxus I get this:

error: `cargo add` could not determine which package to modify. Use the `--package` option to specify a package. 
available packages: freenet-email-inbox, freenet-email-ui, freenet-email-app-web

So I'm not sure how I'm supposed to get Dioxus to run?

**Comment by krionical** [comment]
Figured it out you need: cargo install dioxus-cli. And with that, I finally have the example up! Thanks for the help!
