### ISSUE TITLE
improve freenet library documentation

### ISSUE THREAD

**Issue by gogo2464** [freenet/freenet-core#917]
I have some issues to contribute. I do not understand the goal of some functions. Could you improve some doc please?

**Comment by sanity** [comment]
Not specific enough for an issue.

**Comment by gogo2464** [comment]
I would like to:

- details any potential issue on building and running freenet. EG: tell to ignore tsc errors in the tutorial
- create a use case of real apps
- link api ref from docs.rs for developper directly in https://docs.freenet.org/ for dev
- vulgarize some maths in the last chapter


can you open it again please?

**Comment by gogo2464** [comment]
also the doc there https://docs.freenet.org/introduction.html is already very good! 

I am just wandering if it could respect this typology:

https://www.writethedocs.org/videos/eu/2017/the-four-kinds-of-documentation-and-why-you-need-to-understand-what-they-are-daniele-procida/

**Comment by gogo2464** [comment]
We should also mention that in case of broken issue, the commit got from
```
git reset --hard 8ef468f511c8edc784999778553587b483cfdeb6
```

is stable enough for dev!
