### ISSUE TITLE
Error while building email app

### ISSUE THREAD

**Issue by 9i5BCrUcNX5NmT** [freenet/freenet-core#963]
While build email app i got an error.
## File
"https://github.com/freenet/freenet-core/blob/main/apps/freenet-email-app/Makefile"
## section
"publish-webapp"
## command
"fdev publish --code build/freenet/freenet_email_app_web contract --state build/freenet/contract-state"
## error
"
2024-01-18T21:59:39.608391Z ERROR fdev::commands: Missing export initiate_buffer
2024-01-18T21:59:39.608465Z ERROR stretto::cache::sync: fail to handle clear event: fail to receive msg from channel: fail to receive msg from insert buffer: receiving on an empty and disconnected channel
2024-01-18T21:59:39.608475Z ERROR stretto::cache::sync: fail to handle insert event: fail to receive msg from channel: fail to receive msg from insert buffer: receiving on an empty and disconnected channel
Error: Missing export initiate_buffer
"
![image](https://github.com/freenet/freenet-core/assets/88964539/66b26a2d-d404-4c8f-93e0-379c759a420f)

How can I fix it?

**Comment by gogo2464** [comment]
I got this issue a moment ago.

Could you do `freenet --version` and could you also print your build logs please?

**Comment by 9i5BCrUcNX5NmT** [comment]
[log.txt](https://github.com/freenet/freenet-core/files/14001000/log.txt)
------------------------------------------------------------------------------------------------------------------------
![image](https://github.com/freenet/freenet-core/assets/88964539/00045083-b91b-411e-88d9-ca76d9ca2ca3)
------------------------------------------------------------------------------------------------------------------------
"freenet --version" not working, but it must be 0.0.6
I compiled it on the same day (3 days ago) using "cargo install freenet"

**Comment by gogo2464** [comment]
ah yes sorry I see the issue

**Comment by gogo2464** [comment]
I got the same issue some month ago. You did not build freenet with contract rust feature.

try `cargo build --features contract`

**Comment by gogo2464** [comment]
@9i5BCrUcNX5NmT ahh ok I understand! You should compile freenet from source instead of using cargo.

**Comment by 9i5BCrUcNX5NmT** [comment]
The build is successful after recompile from source.
Thank you.

**Comment by gogo2464** [comment]
very good!!!! you are welcome.
