### ISSUE TITLE
freenet local ; command is absouletly broken

### ISSUE THREAD

**Issue by gogo2464** [freenet/freenet-core#970]
I can push the contract with fdev publish but when I want to reach I have:

failed to get contract XXX, reason: Missing contract and/or parameters

I also got:

```
storing private key file: `identity-manager-key.private.pem`
storing private key file: `identity-manager-key.public.pem`
storing parameters file: `identity-manager-params`
cd /PATH/freenet-core/modules/antiflood-tokens/contracts/token-allocation-record
fdev build
Compiling contract with rust
error: failed to parse lock file at: /PATH/freenet-core/modules/antiflood-tokens/Cargo.lock

Caused by:
  package `freenet-stdlib` is specified twice in the lockfile
Error: exit with status: exit status: 101
make: *** [Makefile:79: build-token-allocation-contract] Error 1
```

not sure if linked. Might be an issue on my side. I had already published and visited 2 sites I created before I recompiled freenet and got this issue.

**Comment by sanity** [comment]
So any contract you push into the network isn't retrievable? And this is a regression of something that worked before?

**Comment by sanity** [comment]
Also, this is the `main` branch?

**Comment by gogo2464** [comment]
> So any contract you push into the network isn't retrievable? And this is a regression of something that worked before?

yes it used to work. it does not work anymore

**Comment by gogo2464** [comment]
yes I tested on the main branch: the contract are not reached anymore

**Comment by gogo2464** [comment]
I did:

```
git clone https://github.com/freenet/freenet-core/ && 
cd freenet-core && 
git submodule update --init --recursive && 
export CARGO_TARGET_DIR="$(pwd)/target" &&
cargo install --path crates/core --force &&
cargo install --path crates/fdev --force &&
cd apps/freenet-microblogging &&
make build && make run-node
```

**Comment by gogo2464** [comment]
And yes NOT any contract is reachable anymore.

**Comment by gogo2464** [comment]
also in order to ensure that you tested right you have to do:

```
cargo clean
rm -Rf "${CARGO_TARGET_DIR}"
rm -rf ~/.local/share/freenet
```

**Comment by gogo2464** [comment]
does the microblogging contract and any contract require antiflood token? Might be the root cause.

Caused by:
  package `freenet-stdlib` is specified twice in the lockfile

**Comment by gogo2464** [comment]
even my reset to 2c5dfd3be25ebfc67fc6cd41fdd4a6adff5d4235 commit does not bring back the web contract fetching

**Comment by iduartgomez** [comment]
Aren't you sure you are not on the wrong stdlib branch?

Do `git submodule update`

**Comment by gogo2464** [comment]
I have done `git submodule update --init --recursive` seems same.

**Comment by gogo2464** [comment]
```
$ cd stdlib/
$ git log -n 3
commit 7729fe328f360067a8ac21fa5809ac0bf748198f (HEAD)
Author: Ignacio Duart <iduartgomez@gmail.com>
Date:   Fri Dec 15 15:36:21 2023 +0100

    New error kind
```

**Comment by gogo2464** [comment]
@sanity did you successfully view the contract after my commands please?

**Comment by sanity** [comment]
@gogo2464: Can you try this in the `modules/antiflood-tokens/contracts/token-allocation-record` directory:

```
$ cargo update
```

That may resolve the problem with the Cargo.lock file.

**Comment by gogo2464** [comment]
it does not. it requires to delet Cargo.lock

**Comment by gogo2464** [comment]
this commit might be responsible of the issue:

https://github.com/freenet/freenet-core/commit/6ef60489e3bd5916f609e8a2b82fc308faca8dbf

the older work. I am looking for more recent

**Comment by gogo2464** [comment]
the commit 8ef468f511c8edc784999778553587b483cfdeb6 works as well

**Comment by gogo2464** [comment]
I am now absolutely 100% sure that the commit https://github.com/freenet/freenet-core/commit/6ef60489e3bd5916f609e8a2b82fc308faca8dbf is responsible of the breaking change!!


the commit just older than this one is running contrary to it

**Comment by gogo2464** [comment]
025b041345be8bf8b8a185f630819a8a1cca5ecc fails

**Comment by gogo2464** [comment]
@iduartgomez could you be assigned to this issue please?

**Comment by netsirius** [comment]
@gogo2464 Apparently, the publish never manages to save the contract due to an issue in the `perform_contract_put` method. By fixing this issue, I have been able to successfully launch the application.
![image](https://github.com/freenet/freenet-core/assets/7628907/efd43123-058e-4a1d-ae12-cb76b31cd6dc)
Now I am verifying that there are no more issues I will upload a fix.

**Comment by gogo2464** [comment]
THANKS @netsirius  !!!

Could you link your pr please? I would like to use it immediately. :)

**Comment by gogo2464** [comment]
https://github.com/freenet/freenet-core/actions/runs/7688432191/job/20949648629?pr=974#step:4:1994


It seems @netsirius , you have to fix it in order to let me finish the testing. https://github.com/freenet/freenet-core/issues/975

**Comment by netsirius** [comment]
@gogo2464 The fix has just been merged. Can you confirm that the issue has been resolved to close it?

**Comment by gogo2464** [comment]
@netsirius sure I am going to. I made a PR to easily build on Linux https://github.com/freenet/freenet-core/pull/974 sadly web-sys has also been broken itself as freenet dependency and the chances it does not impact the new freenet is poor.

**Comment by gogo2464** [comment]
seems to work with the microblogging contract for me. let me try personnal apps!

**Comment by gogo2464** [comment]
I did not test on email app. may be ok. let's close the issue
