### ISSUE TITLE
make freenet even more modular using a socket outproxy instead of websocket?

### ISSUE THREAD

**Issue by gogo2464** [freenet/freenet-core#990]
freenet is a fork of hyphanet. it is made in order to split hosting and networking anonymisation.

It is better because it is more modular.

Could we create a non-web interface so that we could use freenet for video game or what else?

To achieve this I could create 
-GET request that does not returns HTML.
-command that could communicate directely to freenet
--EDIT:

I was wrong. I think,to achieve this I could create socket interface to the out proxy.

**Comment by iduartgomez** [comment]
Websocket API is what this is for and they don't return html... Other protocols may be supported in the future (like unix sockets, dbus, or some RPC protocol) but not planned for now.
